### ISSUE TITLE
The upstream project does not compile with ffmpeg >= 5

### ISSUE THREAD

**Issue by traversaro** [conda-forge/openscenegraph-feedstock#29]
I opened a separate issue as otherwise the information may be lost as migration PRs are constantely be closed and re-opened.

Apparently there is not a lot interest for this upstream, see https://github.com/openscenegraph/OpenSceneGraph/issues/1111. If there is no interest in fixing this, probably the easiest way forward is just to disable the ffmpeg plugin, as for example Ubuntu since 22.10 handled this: https://launchpad.net/ubuntu/+source/openscenegraph/3.6.5+dfsg1-7ubuntu1 .

Actually it seems that the only user of openscenegraph in conda-forge is actually using ffmpeg https://github.com/search?q=repo%3AGepetto%2Fgepetto-viewer%20ffmpeg&type=code . @jcarpent @ymontmarin  it is possible somehow to use gepetto-viewer without ffmpeg? Otherwise I am afraid that to go forward with the ffmpeg 5.0 migration, the only way is to leave behind this package. Note that there is a similar situation even using apt for Ubuntu >= 22.10, as also there the only ffmpeg available is 5.

**Comment by ymontmarin** [comment]
Hi @traversaro , I will dig into this. During this time, this package can be left behind from the global ffmpeg migration.

**Comment by traversaro** [comment]
Thanks @ymontmarin !

**Comment by h-vetinari** [comment]
Just saw that openscenegraph is [legacy](https://github.com/openscenegraph/OpenSceneGraph/discussions/1176) and has been replaced by [VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph)... So it doesn't sound like this will be tackled soon or at all, which puts us in quite a bit of pain, until everyone has moved on to VSG...

**Comment by ymontmarin** [comment]
@h-vetinari This is a subject I raised with the core team of the HPP and gepetto stack and this is still in discussion, but it will not move quickly...

I think the HPP stack is doomed to use old assimp and ffmpeg while still on OSG

**Comment by h-vetinari** [comment]
> I think the HPP stack is doomed to use old assimp and ffmpeg while still on OSG

There's only 2-3 packages missing in the assimp/boost migrations now (stuck on https://github.com/conda-forge/gepetto-viewer-feedstock/pull/38), but yeah, getting the whole stack sounds like it won't happen. Is there a way to use gepetto without ffmpeg, or is that just completely broken?

**Comment by ymontmarin** [comment]
Sadly, we need ffmpeg for gepetto

**Comment by jslee02** [comment]
> > I think the HPP stack is doomed to use old assimp and ffmpeg while still on OSG
> 
> There's only 2-3 packages missing in the assimp/boost migrations now (stuck on [conda-forge/gepetto-viewer-feedstock#38](https://github.com/conda-forge/gepetto-viewer-feedstock/pull/38)), but yeah, getting the whole stack sounds like it won't happen. Is there a way to use gepetto without ffmpeg, or is that just completely broken?

Adding a variant that has no ffmpeg dependency: https://github.com/conda-forge/openscenegraph-feedstock/pull/36

**Comment by traversaro** [comment]
> Sadly, we need ffmpeg for gepetto

Are you sure? I was looking a bit on update on this issue triggered by @jslee02 comment, and it seems that in Ubuntu 24.04 apt packages the ffmpeg plugin of osg was disabled (see https://git.launchpad.net/ubuntu/+source/openscenegraph/commit/?h=ubuntu/noble&id=a453c15270e96863f6c174c2ad1f6bf08e917111), and in indeed I can't find it in the apt osg package in Ubuntu 24.04 : 

~~~
traversaro@IITBMP014LW012:~$ dpkg -L libopenscenegraph161 | grep ffmpeg
traversaro@IITBMP014LW012:~$
~~~

Furthermore, looking at gepetto-viewer, I may be wrong but it seems that it is using ffmpeg, but just invoking directly the ffmpeg command (see https://github.com/search?q=repo%3AGepetto%2Fgepetto-viewer%20ffmpeg&type=code), not via the osg ffmpeg plugin based on `AudioStream` or `ImageStream` (see https://github.com/search?q=repo%3AGepetto%2Fgepetto-viewer+ImageStream&type=code).

@ymontmarin @jcarpent  As far as you know is anyone using gepetto-viewer on Ubuntu 24.04 with apt dependencies? If that works fine, probably it is an indication that the ffmpeg plugin of openscenegraph is not used, and so we can drop its compilation here as well? Just asking so we can streamline the maintenance of this package, if we can just have a single package instead of incompatible -noffmpeg and a -ffmpeg4 variants it would be much easier to manage the feedstock.

**Comment by traversaro** [comment]
I also opened a similar issue on the gepetto-viewer issue tracker: https://github.com/Gepetto/gepetto-viewer/issues/226, as it may be of interest also for packagers of different ecosystem (nix, apt, aur).

**Comment by ymontmarin** [comment]
@traversaro I take the point !

**Comment by ymontmarin** [comment]
I study in this PR: https://github.com/conda-forge/gepetto-viewer-feedstock/pull/48 how we can get rid of ffmpeg

**Comment by traversaro** [comment]
> I study in this PR: [conda-forge/gepetto-viewer-feedstock#48](https://github.com/conda-forge/gepetto-viewer-feedstock/pull/48) how we can get rid of ffmpeg

Perfect! I will open a PR instead here to drop the ffmpeg dependency.

**Comment by ymontmarin** [comment]
> Sadly, we need ffmpeg for gepetto

@traversaro I am very sorry for this confusion, I was convinced the dependency was deeper and do not know from where I had this belief.

**Comment by traversaro** [comment]
No problem at all, it is easy to get lost with huge dependency trees, thanks for all the effort in the maintenance of gepetto-related conda packages!

**Comment by ymontmarin** [comment]
Should we close this issue now then ?

**Comment by traversaro** [comment]
It will be closed automatically once https://github.com/conda-forge/openscenegraph-feedstock/pull/42 is merged.
